[server]
headless = true
address = "0.0.0.0"
port = 5000

# Light Theme
[theme]
primaryColor = "#4480c4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"